### ISSUE TITLE
Wallapop search always returns default sorting

### ISSUE THREAD

**Issue by gabrifc** [tanrax/wallapop-alert#4]
Hi! 

When searching for new items in the wallapop site, (e.g. gameboy - http://es.wallapop.com/search?kws=gameboy&lat=41.398077&lng=2.170432#minPrice=&maxPrice=&dist=0_&order=creationDate-des&kws=gameboy&lat=41.398077&lng=2.170432), the html response from the server is always the search without filters and default distance sorting (http://es.wallapop.com/search?kws=gameboy&lat=&lng=).

After a few seconds, the product list gets updated with the custom sorting (e.g. new products first) and other filters via JS. 

Therefore, this script will only notify new items if they are new in the default filters and sorting.

I used to workaround this using selenium with the phantomJS browser in a virtualdisplay and waiting aprox. 6 seconds for the page to load before reading the source and parse it with bs4. 

Your approach with demiurge is much cleaner and cheaper in terms of resources, but can it be adapted to return the updated results?

**Comment by tanrax** [comment]
Hi!

You're right. Javascript required to apply filters. The only way would be to run the address with pyv8 and then give it to demiurge.

**Comment by gabrifc** [comment]
Thanks! 

I'll check pyv8. I guess I'll have to use the rest api for now...

**Comment by gabrifc** [comment]
Wrote a simple solution today, see [here](https://github.com/gabrifc/wallapop-alert/blob/master/wallapop_alert.py). 

Also reduces the number of http calls and provides much more info.

The rest url seems to be `/rest/items?minPrice=&maxPrice=&dist=0_&order=creationDate-des&lat=41.398077&lng=2.170432&kws=`

**Comment by tanrax** [comment]
Good job! With that new route you can already try a simple json !!

**Comment by tanrax** [comment]
I implemented all the improvements and made a web. I invite you to go https://wallaviso.com/ :)
