### ISSUE TITLE
No funciona

### ISSUE THREAD

**Issue by magarto** [tanrax/wallapop-alert#5]
Buenas, intento meter la siguiente url y no me va:
http://es.wallapop.com/search?kws=new+3ds+xl&lat=41.398077&lng=2.170432#minPrice=70&maxPrice=150&dist=0_&order=creationDate-des&kws=new+3ds+xl&lat=41.398077&lng=2.170432

He cambiado la línea de urlSearch a:
`urlSearch = 'http://es.wallapop.com/search?kws=new+3ds+xl&lat=41.398077&lng=2.170432#minPrice=70&maxPrice=150&dist=0_&order=creationDate-des&kws=new+3ds+xl&lat=41.398077&lng=2.170432`'

Me reporta el siguiente error:
```
  File "./wallapop_alert.py", line 126
    wallAlert(urlSearch)
                       ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by magarto** [comment]
También he probado con las dos siguientes:

`urlSearch = 'http://es.wallapop.com/search?kws' + keyword + '&minPrice=70&maxPrice=150&dist=0_&order=creationDate-des&lat=41.398077&lng=2.170432'`
y luego ejecutando el comando con -k new+3ds+xl

Y también con:
`urlSearch = 'http://es.wallapop.com/search?kws' + new+3ds+xl + '&minPrice=70&maxPrice=150&dist=0_&order=creationDate-des&lat=41.398077&lng=2.170432'`
y
`urlSearch = 'http://es.wallapop.com/search?kws' + 'new+3ds+xl' + '&minPrice=70&maxPrice=150&dist=0_&order=creationDate-des&lat=41.398077&lng=2.170432'`

**Comment by tanrax** [comment]
Estas tabulando mal el código. Revísalo.
En el segundo estas utilizando una variable inválida. Tendrás que ponerla entre comillas para conventirla en un string.
No es un bug, sino un problema de programación. Cierro.

**Comment by magarto** [comment]
Ok, gracias. Entonces cómo se pondría en mi caso? Gracias

**Comment by tanrax** [comment]
No es el lugar adecuado. Tendrás que consultarlo en un Foro de Python :)

**Comment by magarto** [comment]
Ok, es que como indicas que solo hay que meter el enlace y haciendo eso no funciona tal cual está el código...

**Comment by tanrax** [comment]
Y funciona. Pero, lamentablemente, estas introduciendo elementos no válidos por el propio lenguaje. No por mi código. 
Te invito a consultar en algún foro esta duda y aprender.
Gracias
